### ISSUE TITLE
建议把配着的资料也拉下来

### ISSUE THREAD

**Issue by RanKKI** [chinese-pill/chinese-pill#1]
比如第一份的视频, 万一原po删了 还有备份.. 也就更有说服力..

**Comment by Steve-Mr** [comment]
附议

**Comment by SykieChen** [comment]
多谢建议。鉴于安全原因，不打算收集被官方删除的新闻，只是在合法合规的范围内收集允许发布的新闻。因此被删除的可能性不大。如果原始链接失效的情况增多的话，会考虑重传视频。再次感谢。
